# Generated by Django 4.1.7 on 2023-03-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=200, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=200, verbose_name='Příjmení')),
            ],
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=180, verbose_name='Typ pojištění')),
                ('limit', models.CharField(max_length=150, verbose_name='Pojistný limit')),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni.pojistenec')),
            ],
        ),
    ]
