# Generated by Django 4.1.7 on 2023-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='limit',
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='email',
            field=models.CharField(default='ja@seznam.cz', max_length=150, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='psc',
            field=models.CharField(default='12345', max_length=100, verbose_name='PSČ'),
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='telefon',
            field=models.CharField(default=123456789, max_length=150, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='ulice',
            field=models.CharField(default='Nová 1', max_length=200, verbose_name='Ulice a číslo popisné'),
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='castka',
            field=models.CharField(default=100000, max_length=150, verbose_name='Částka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.CharField(default='1.1.2024', max_length=100, verbose_name='Platnost do'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.CharField(default='1.1.2024', max_length=100, verbose_name='Platnost od'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='predmet',
            field=models.CharField(default='byt', max_length=150, verbose_name='Předmět pojištění'),
            preserve_default=False,
        ),
    ]
