# Generated by Django 4.1.7 on 2023-03-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0002_remove_pojisteni_limit_pojistenec_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojistenec',
            options={'verbose_name': 'Pojištěnec', 'verbose_name_plural': 'Pojištěnci'},
        ),
        migrations.AlterModelOptions(
            name='pojisteni',
            options={'verbose_name': 'POjištění', 'verbose_name_plural': 'Pojištění'},
        ),
    ]
