# Generated by Django 4.1.7 on 2023-03-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0003_alter_pojistenec_options_alter_pojisteni_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='pojistenec',
        ),
    ]
