# Generated by Django 4.1.7 on 2023-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0004_remove_pojisteni_pojistenec'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojistenec',
            name='mesto',
            field=models.CharField(default='mesto', max_length=100, verbose_name='Město'),
            preserve_default=False,
        ),
    ]
