# Generated by Django 4.1.7 on 2023-03-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0005_pojistenec_mesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='email',
            field=models.CharField(max_length=150, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='psc',
            field=models.CharField(max_length=100, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='telefon',
            field=models.CharField(max_length=150, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='ulice',
            field=models.CharField(max_length=200, verbose_name='Ulice a číslo popisné'),
        ),
    ]
