# Generated by Django 4.1.7 on 2023-03-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0006_alter_pojistenec_email_alter_pojistenec_psc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojisteni',
            options={'verbose_name': 'Pojištění', 'verbose_name_plural': 'Pojištění'},
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='pojisteni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojisteni.pojisteni', verbose_name='Sjednaná pojištění'),
        ),
    ]
