# Generated by Django 4.1.7 on 2023-04-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0008_uzivatel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojistenec',
            name='pojisteni',
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='pojisteni',
            field=models.ManyToManyField(to='pojisteni.pojisteni'),
        ),
    ]
