# Generated by Django 4.1.7 on 2023-04-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0009_remove_pojistenec_pojisteni_pojistenec_pojisteni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojistenec',
            old_name='pojisteni',
            new_name='jaka_pojisteni',
        ),
    ]
