# Generated by Django 4.1.7 on 2023-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0011_alter_pojistenec_jaka_pojisteni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='email',
            field=models.CharField(max_length=30, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='jaka_pojisteni',
            field=models.ManyToManyField(to='pojisteni.pojisteni'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='jmeno',
            field=models.CharField(max_length=20, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='mesto',
            field=models.CharField(max_length=20, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='prijmeni',
            field=models.CharField(max_length=20, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='psc',
            field=models.CharField(max_length=6, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='telefon',
            field=models.CharField(max_length=13, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='ulice',
            field=models.CharField(max_length=20, verbose_name='Ulice a číslo popisné'),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='castka',
            field=models.CharField(max_length=20, verbose_name='Částka'),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.CharField(max_length=10, verbose_name='Platnost do'),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.CharField(max_length=10, verbose_name='Platnost od'),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='predmet',
            field=models.CharField(max_length=20, verbose_name='Předmět pojištění'),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='typ',
            field=models.CharField(max_length=20, verbose_name='Typ pojištění'),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
