# Generated by Django 4.1.7 on 2023-04-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0012_alter_pojistenec_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojistenec',
            name='jaka_pojisteni',
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='pojisteny',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pojisteni.pojistenec', verbose_name='Pojištěný'),
        ),
    ]
