# Generated by Django 4.1.7 on 2023-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0013_remove_pojistenec_jaka_pojisteni_pojisteni_pojisteny'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojistenec',
            options={'verbose_name': 'Pojištěnec'},
        ),
        migrations.RemoveField(
            model_name='pojisteni',
            name='pojisteny',
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='jaka_pojisteni',
            field=models.ManyToManyField(to='pojisteni.pojisteni'),
        ),
    ]
